Feature/admin page
chain-labs/simplr-events pull request #12
Opened 2023-02-23 17:52 UTC by Khushboo1008

2023-02-24 14:50 UTC, codebuster22 requested changes

2023-02-24 14:50 UTC, codebuster22 commented on src/containers/admin/components/ConfirmButton.tsx
> +              response = await addChunk(chunk, nextBatchId)
what if the response is 201 here, that means Email wasn't sent but still you are sending more

2023-02-24 14:50 UTC, codebuster22 commented on src/containers/admin/components/ConfirmButton.tsx
> +              response = await addChunk(chunk, nextBatchId)
same

2023-02-24 17:12 UTC, codebuster22 requested changes
Make variables more descriptive. Cannot merge if variables are not understandable.

2023-02-24 17:12 UTC, codebuster22 commented on src/containers/admin/components/ConfirmButton.tsx
> +  const MAX_SIZE = 25
What max size are we talking about. Either add comment or make variable more descriptive

2023-02-24 17:12 UTC, codebuster22 commented on src/containers/admin/components/ConfirmButton.tsx
> +  const addChunk = async (chunk, nextBatchId) => {
Add comments on what this function does

2023-02-24 17:12 UTC, codebuster22 commented on src/containers/admin/components/ConfirmButton.tsx
> +        const size = batch.inputParams.length
What does size represent. Make variable descriptive

2023-02-24 17:12 UTC, codebuster22 commented on src/containers/admin/components/ConfirmButton.tsx
> +          let response
What response is this. Make it more descriptive

2023-02-24 17:12 UTC, codebuster22 commented on src/containers/admin/components/ConfirmButton.tsx
> +          const ActualSize = Math.floor(size / MAX_SIZE)
What does actual size represent? Make it more descriptive

2023-02-24 18:10 UTC, codebuster22 approved these changes
Skimmed it, but it looks better now

2023-02-25 08:03 UTC, angel112 approved these changes

2023-02-25 18:12 UTC, merged