Feature/verify page
chain-labs/simplr-events pull request #13
Opened 2023-02-28 22:51 UTC by Khushboo1008

2023-03-01 16:11 UTC, codebuster22 requested changes
looks good, but some changes required.

2023-03-01 16:11 UTC, codebuster22 commented on src/containers/verify/components/Login.tsx
> +// const STATIC_PASSWORD =
is this comment required?

2023-03-01 16:11 UTC, codebuster22 commented on src/containers/verify/components/Login.tsx
> +    console.log(hash)
can you log it properly? Describe what this is logging so we can debug properly.

2023-03-01 16:11 UTC, codebuster22 commented on src/containers/verify/components/Login.tsx
> +      console.log('valid')
what is valid

2023-03-01 16:11 UTC, codebuster22 commented on src/containers/verify/components/Login.tsx
> +      setTimeout(changeStep, 4000)
why do we wait for 4 seconds before moving to next step?

2023-03-01 16:11 UTC, codebuster22 commented on src/containers/verify/components/Login.tsx
> +    dispatch(setStep(1))
define steps as String constants or enums. No numbers.
What step are we setting it to?

2023-03-01 16:11 UTC, codebuster22 commented on src/containers/verify/components/QrScan.tsx
> +    console.log(signerAddress)
what does this log say? How will this help in debugging?

2023-03-01 16:45 UTC, angel112 commented on src/containers/verify/components/Login.tsx
> +    console.log(hash)
wrap it like `console.log({ hash })` and you can name it as well like `console.log({ name: hash })`

2023-03-02 07:08 UTC, codebuster22 commented on src/containers/verify/components/Login.tsx
> +    console.log(hash)
I would suggest adding a string description: 
"Login hash: "

2023-03-02 07:10 UTC, codebuster22 commented on src/containers/verify/components/Login.tsx
> +    const salt = bcrypt.genSaltSync(10)
magic value. Remove it.

2023-03-02 07:19 UTC, codebuster22 commented on src/containers/verify/components/QrScan.tsx
> +      setErrorOcurred(true)
What error occurred?

2023-03-02 07:20 UTC, codebuster22 commented on src/containers/verify/components/QrScan.tsx
> +      setError('Owner is not valid')
Error string should be constant.

2023-03-02 07:25 UTC, codebuster22 requested changes

2023-03-02 07:25 UTC, codebuster22 commented on src/containers/verify/components/QrScan.tsx
> +      setError('Owner is not valid')
example
```export const ERROR_OWNER_NOT_VALID = "Owner is not valid";```

2023-03-02 07:25 UTC, codebuster22 commented on src/containers/verify/components/QrScan.tsx
> +    const id = `ticket-${contractAddress}-${tokenId}`
this can be converted to pure function. To ensure generation of ticket ID is consistent everywhere

2023-03-02 19:17 UTC, codebuster22 requested changes

2023-03-02 19:17 UTC, codebuster22 commented on package.json
> +    "bcrypt": "^5.1.0",
If we are not using, can we remove it?

2023-03-02 19:23 UTC, codebuster22 requested changes

2023-03-02 19:23 UTC, codebuster22 commented on src/containers/verify/components/Login.tsx
> +// const STATIC_PASSWORD =
can this comment be removed?

2023-03-02 19:23 UTC, codebuster22 commented on src/containers/verify/components/Login.tsx
> +    const salt = bcrypt.genSaltSync(10)
still using magic value?

2023-03-03 15:29 UTC, codebuster22 approved these changes
lgtm

2023-03-03 19:42 UTC, merged